apiVersion: apps/v1
kind: Deployment
metadata:
  name: halort-design-system
  labels:
    app: halort-design-system
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: halort-design-system
  template:
    metadata:
      labels:
        app: halort-design-system
    spec:
      imagePullSecrets:
        - name: ghcr-io-pull
      containers:
        - name: halort-design-system
          image: ghcr.io/halort/halort-design-system:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 3
