apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: halort
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
commonLabels:
  app.kubernetes.io/name: halort-design-system
  app.kubernetes.io/part-of: halort
images:
  - name: ghcr.io/halort/halort-design-system
    newTag: d5898fd9588e6d2d033a7281bfe350ddf61bef2e
