apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: halort
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
commonLabels:
  app.kubernetes.io/name: halort-design-system
  app.kubernetes.io/part-of: halort
images:
  - name: ghcr.io/halort/halort-design-system
    newTag: 6a27507c7085651f33cfa1a332b918a235c5023e
