import StyleDictionary from "style-dictionary";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");
const dist = path.join(root, "dist");

StyleDictionary.registerFormat({
  name: "css/variables-themed",
  format({ dictionary }) {
    const darkVars = dictionary.allTokens
      .filter((t) => t.path[0] === "color" && t.path[1] === "dark")
      .map((t) => `  --${t.path.slice(2).join("-")}: ${t.value};`)
      .join("\n");

    const lightVars = dictionary.allTokens
      .filter((t) => t.path[0] === "color" && t.path[1] === "light")
      .map((t) => `  --${t.path.slice(2).join("-")}: ${t.value};`)
      .join("\n");

    const spacingVars = dictionary.allTokens
      .filter((t) => t.path[0] === "spacing")
      .map((t) => `  --spacing-${t.path[1]}: ${t.value};`)
      .join("\n");

    const radiusVars = dictionary.allTokens
      .filter((t) => t.path[0] === "radius")
      .map((t) => `  --radius-${t.path[1]}: ${t.value};`)
      .join("\n");

    return `/* Generated by Style Dictionary — do not edit directly */
:root,
[data-theme="dark"] {
${darkVars}
${spacingVars}
${radiusVars}
}

[data-theme="light"] {
${lightVars}
}
`;
  },
});

StyleDictionary.registerFormat({
  name: "tailwind/theme-inline",
  format() {
    const colorMappings = [
      "background",
      "foreground",
      "muted",
      "surface",
      "surface-muted",
      "surface-elevated",
      "surface-dark",
      "border",
      "primary",
      "primary-light",
      "primary-dark",
      "accent",
      "accent-light",
      "accent-dark",
      "primary-foreground",
      "success",
      "warning",
      "danger",
    ];

    const themeBlock = colorMappings
      .map((name) => `  --color-${name}: var(--${name});`)
      .join("\n");

    return `@theme inline {
${themeBlock}
  --font-sans: var(--font-geist-sans, Geist, ui-sans-serif, system-ui, sans-serif);
  --font-mono: var(--font-geist-mono, Geist Mono, ui-monospace, monospace);
}
`;
  },
});

const sd = new StyleDictionary({
  source: [path.join(root, "src/tokens.json")],
  platforms: {
    css: {
      transformGroup: "css",
      buildPath: path.join(dist, "css/"),
      files: [{ destination: "variables.css", format: "css/variables-themed" }],
    },
    tailwind: {
      transformGroup: "css",
      buildPath: path.join(dist, "tailwind/"),
      files: [{ destination: "theme.css", format: "tailwind/theme-inline" }],
    },
  },
});

await sd.buildAllPlatforms();
console.log("✓ Design tokens CSS generated");
